[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NPM_CONFIG_PRODUCTION = "false"
NODE_ENV = "production"

[[services]]
name = "QAapp"

[services.env]
MONGODB_URI = "${{ MongoDB-6Ke1.MONGO_URL }}"
JWT_SECRET = "your-super-secret-jwt-key-for-production-qa-testing-system"
UPLOAD_DIR = "/data/uploads"

[[volumes]]
name = "data"
mountPath = "/data"