[build]
builder = "NIXPACKS"

[deploy]
buildCommand = "npm ci --include=dev && npm --prefix pwa ci --include=dev && npm --prefix dashboard ci --include=dev && npm run build"

[variables]
PORT = "3000"
NODE_ENV = "production"
DB_FILE = "/data/qa_testing.db"
UPLOAD_DIR = "/data/uploads"
NPM_CONFIG_PRODUCTION = "false"

# Persistent volume for database and uploads
[[volumes]]
name = "data"
mountPath = "/data"
sizeGB = 1
